services:
  # react-app:
  #   image: react-app
  #   build: ./client
  #   stdin_open: true
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - mern-app

  node-web-api:
    image: node-web-api
    build: .
    ports:
      - "4000:4000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge